### ISSUE TITLE
6月のアップデート

### ISSUE THREAD

**Issue by ktaroabobon** [ktaroabobon/iccepm2024#111]
# ToDo

- [x] 表紙のページ更新→ Conference Brochureに表記変更
- [x] ページの野城先生の所属について→東京都市大学学長、東京大学、に表記変更
- [x] 登録ページの「登録」ボタン→ 「チェックイン」ボタン、に表記変更
